name: terraform-plan-json

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # necessário para OIDC no Azure/login

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/terraform

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Login no Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Criar pasta de saída (dist)
        run: mkdir -p dist

      - name: Terraform Plan (gera arquivo binário do plano)
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform plan -input=false -no-color -out=dist/tfplan

      - name: Converter plano para JSON (plan.json)
        run: terraform show -json dist/tfplan > dist/plan.json

      - name: Publicar plan.json como Artifact (sempre)
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: terraform-plan-json
          path: dist/plan.json
          retention-days: 7



          #adicionado para gerar evidência de conformidade via OPA
      - name: Instalar OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 1.7.1

      - name: Enforce OPA policy no plan.json (falha se houver deny)
        shell: bash
        run: |
          set -euo pipefail

          test -f dist/plan.json

          DENY_COUNT=$(opa eval -i dist/plan.json -d ../../policies -f raw \
            'count(data.azure.tagging.require_tags.deny)')

          echo "deny_count=$DENY_COUNT"

          if [ "$DENY_COUNT" -gt 0 ]; then
            echo "Policy violations:"
            opa eval -i dist/plan.json -d ../../policies -f pretty \
              'data.azure.tagging.require_tags.deny'
            exit 1
          fi

      - name: Publicar plan.json como Artifact (sempre)
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: terraform-plan-json
          path: examples/terraform/dist/plan.json
          retention-days: 7
          if-no-files-found: warn


